GET http://localhost:3000/todos/
###

GET http://localhost:3000/todos/7/
###


GET http://localhost:3000/agenda/?date=2021-01-28
###

POST http://localhost:3000/todos/
Content-Type: application/json

{
 "id": 7,
 "todo": "Finalize event SEKHAR theme",
 "priority": "HIGH",
 "status": "TO DO",
 "category": "HOME",
 "dueDate": "2021-01-28"
}


###


PUT http://localhost:3000/todos/7/
Content-Type: application/json

{
"dueDate": "2021-08-28"
}
###

DELETE http://localhost:3000/todos/7/
###